//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocTypeLookupService
{

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace = "http://njm.com/esb/gcpip/doc/1.0/interfaces/DocTypeLookupService", ConfigurationName = "DocTypeLookupService")]
    public interface DocTypeLookupService
    {

        // CODEGEN: Generating message contract since the operation lookupDocType is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponseMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequestMessage))]
        lookupDocTypeResponse1 lookupDocType(lookupDocTypeRequest request);

        [System.ServiceModel.OperationContractAttribute(Action = "", ReplyAction = "*")]
        System.Threading.Tasks.Task<lookupDocTypeResponse1> lookupDocTypeAsync(lookupDocTypeRequest request);
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://njm.com/esb/gcpip/doc/1.0/interfaces/DocTypeLookupService")]
    public partial class lookupDocType
    {

        private DocTypeRequest requestField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public DocTypeRequest request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/gcpip/doc/1.0/types")]
    public partial class DocTypeRequest : AbstractRequestMessage
    {

        private DocType docTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public DocType DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/gcpip/doc/1.0/types")]
    public partial class DocType
    {

        private int docTypeIDField;

        private bool docTypeIDFieldSpecified;

        private string docTypeNameField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public int DocTypeID
        {
            get
            {
                return this.docTypeIDField;
            }
            set
            {
                this.docTypeIDField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DocTypeIDSpecified
        {
            get
            {
                return this.docTypeIDFieldSpecified;
            }
            set
            {
                this.docTypeIDFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string DocTypeName
        {
            get
            {
                return this.docTypeNameField;
            }
            set
            {
                this.docTypeNameField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/common/1.0.0/types")]
    public partial class ErrorInformation
    {

        private string systemIdField;

        private string codeTxField;

        private string messageTxField;

        private ErrorInformation causeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string SystemId
        {
            get
            {
                return this.systemIdField;
            }
            set
            {
                this.systemIdField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public string CodeTx
        {
            get
            {
                return this.codeTxField;
            }
            set
            {
                this.codeTxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public string MessageTx
        {
            get
            {
                return this.messageTxField;
            }
            set
            {
                this.messageTxField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 3)]
        public ErrorInformation Cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/common/1.0.0/types")]
    public partial class ResponseHeader
    {

        private CorrelationContext correlationContextField;

        private bool errorInField;

        private bool errorInFieldSpecified;

        private ErrorInformation errorInformationField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public CorrelationContext CorrelationContext
        {
            get
            {
                return this.correlationContextField;
            }
            set
            {
                this.correlationContextField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 1)]
        public bool ErrorIn
        {
            get
            {
                return this.errorInField;
            }
            set
            {
                this.errorInField = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorInSpecified
        {
            get
            {
                return this.errorInFieldSpecified;
            }
            set
            {
                this.errorInFieldSpecified = value;
            }
        }

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 2)]
        public ErrorInformation ErrorInformation
        {
            get
            {
                return this.errorInformationField;
            }
            set
            {
                this.errorInformationField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/common/1.0.0/types")]
    public partial class CorrelationContext
    {

        private string correlationIdField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public string CorrelationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocTypeResponse))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/common/1.0.0/types")]
    public partial class AbstractResponseMessage
    {

        private ResponseHeader headerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public ResponseHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/gcpip/doc/1.0/types")]
    public partial class DocTypeResponse : AbstractResponseMessage
    {

        private DocType docTypeField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public DocType DocType
        {
            get
            {
                return this.docTypeField;
            }
            set
            {
                this.docTypeField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/common/1.0.0/types")]
    public partial class RequestHeader
    {

        private CorrelationContext correlationContextField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public CorrelationContext CorrelationContext
        {
            get
            {
                return this.correlationContextField;
            }
            set
            {
                this.correlationContextField = value;
            }
        }
    }

    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(DocTypeRequest))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace = "http://njm.com/esb/common/1.0.0/types")]
    public partial class AbstractRequestMessage
    {

        private RequestHeader headerField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, Order = 0)]
        public RequestHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType = true, Namespace = "http://njm.com/esb/gcpip/doc/1.0/interfaces/DocTypeLookupService")]
    public partial class lookupDocTypeResponse
    {

        private DocTypeResponse responseField;

        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form = System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable = true, Order = 0)]
        public DocTypeResponse response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class lookupDocTypeRequest
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://njm.com/esb/gcpip/doc/1.0/interfaces/DocTypeLookupService", Order = 0)]
        public lookupDocType lookupDocType;

        public lookupDocTypeRequest()
        {
        }

        public lookupDocTypeRequest(lookupDocType lookupDocType)
        {
            this.lookupDocType = lookupDocType;
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped = false)]
    public partial class lookupDocTypeResponse1
    {

        [System.ServiceModel.MessageBodyMemberAttribute(Namespace = "http://njm.com/esb/gcpip/doc/1.0/interfaces/DocTypeLookupService", Order = 0)]
        public lookupDocTypeResponse lookupDocTypeResponse;

        public lookupDocTypeResponse1()
        {
        }

        public lookupDocTypeResponse1(lookupDocTypeResponse lookupDocTypeResponse)
        {
            this.lookupDocTypeResponse = lookupDocTypeResponse;
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocTypeLookupServiceChannel : DocTypeLookupService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocTypeLookupServiceClient : System.ServiceModel.ClientBase<DocTypeLookupService>, DocTypeLookupService
    {

        public DocTypeLookupServiceClient()
        {
        }

        public DocTypeLookupServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public DocTypeLookupServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DocTypeLookupServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public DocTypeLookupServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        lookupDocTypeResponse1 DocTypeLookupService.lookupDocType(lookupDocTypeRequest request)
        {
            return base.Channel.lookupDocType(request);
        }

        public lookupDocTypeResponse lookupDocType(lookupDocType lookupDocType1)
        {
            lookupDocTypeRequest inValue = new lookupDocTypeRequest();
            inValue.lookupDocType = lookupDocType1;
            lookupDocTypeResponse1 retVal = ((DocTypeLookupService)(this)).lookupDocType(inValue);
            return retVal.lookupDocTypeResponse;
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<lookupDocTypeResponse1> DocTypeLookupService.lookupDocTypeAsync(lookupDocTypeRequest request)
        {
            return base.Channel.lookupDocTypeAsync(request);
        }

        public System.Threading.Tasks.Task<lookupDocTypeResponse1> lookupDocTypeAsync(lookupDocType lookupDocType)
        {
            lookupDocTypeRequest inValue = new lookupDocTypeRequest();
            inValue.lookupDocType = lookupDocType;
            return ((DocTypeLookupService)(this)).lookupDocTypeAsync(inValue);
        }
    }
}