//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnBaseService
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://njm.com/ccutil/1.0.0/interfaces", ConfigurationName="OnBaseService.DocumentData")]
    public interface DocumentData
    {
        
        // CODEGEN: Generating message contract since the operation getDocumentTypeIdByName is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractResponseMessage))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(AbstractRequestMessage))]
        OnBaseService.getDocumentTypeIdByNameResponse1 getDocumentTypeIdByName(OnBaseService.getDocumentTypeIdByNameRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<OnBaseService.getDocumentTypeIdByNameResponse1> getDocumentTypeIdByNameAsync(OnBaseService.getDocumentTypeIdByNameRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://njm.com/ccutil/1.0.0/interfaces")]
    public partial class getDocumentTypeIdByName
    {
        
        private OnBaseDataRequestMessage requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public OnBaseDataRequestMessage request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/ccutil/1.0.0/types")]
    public partial class OnBaseDataRequestMessage : AbstractRequestMessage
    {
        
        private OnbaseDataRequest requestField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OnbaseDataRequest Request
        {
            get
            {
                return this.requestField;
            }
            set
            {
                this.requestField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/ccutil/1.0.0/types")]
    public partial class OnbaseDataRequest
    {
        
        private string docNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DocName
        {
            get
            {
                return this.docNameField;
            }
            set
            {
                this.docNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/ccutil/1.0.0/types")]
    public partial class OnbaseDataResponse
    {
        
        private string docIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string DocId
        {
            get
            {
                return this.docIdField;
            }
            set
            {
                this.docIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/1.0.0/types")]
    public partial class ErrorInformation
    {
        
        private string systemIdField;
        
        private ErrorCodes codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SystemId
        {
            get
            {
                return this.systemIdField;
            }
            set
            {
                this.systemIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorCodes Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/1.0.0/types")]
    public enum ErrorCodes
    {
        
        /// <remarks/>
        OK,
        
        /// <remarks/>
        NoData,
        
        /// <remarks/>
        NoService,
        
        /// <remarks/>
        Unknown,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/1.0.0/types")]
    public partial class ResponseHeader
    {
        
        private CorrelationContext correlationContextField;
        
        private bool errorInField;
        
        private bool errorInFieldSpecified;
        
        private ErrorInformation errorInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CorrelationContext CorrelationContext
        {
            get
            {
                return this.correlationContextField;
            }
            set
            {
                this.correlationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public bool ErrorIn
        {
            get
            {
                return this.errorInField;
            }
            set
            {
                this.errorInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorInSpecified
        {
            get
            {
                return this.errorInFieldSpecified;
            }
            set
            {
                this.errorInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ErrorInformation ErrorInformation
        {
            get
            {
                return this.errorInformationField;
            }
            set
            {
                this.errorInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/1.0.0/types")]
    public partial class CorrelationContext
    {
        
        private string correlationIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CorrelationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OnBaseDataResponseMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/1.0.0/types")]
    public partial class AbstractResponseMessage
    {
        
        private ResponseHeader headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ResponseHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/ccutil/1.0.0/types")]
    public partial class OnBaseDataResponseMessage : AbstractResponseMessage
    {
        
        private OnbaseDataResponse responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public OnbaseDataResponse Response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/1.0.0/types")]
    public partial class RequestHeader
    {
        
        private CorrelationContext correlationContextField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public CorrelationContext CorrelationContext
        {
            get
            {
                return this.correlationContextField;
            }
            set
            {
                this.correlationContextField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(OnBaseDataRequestMessage))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/1.0.0/types")]
    public partial class AbstractRequestMessage
    {
        
        private RequestHeader headerField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public RequestHeader Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://njm.com/ccutil/1.0.0/interfaces")]
    public partial class getDocumentTypeIdByNameResponse
    {
        
        private OnBaseDataResponseMessage responseField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public OnBaseDataResponseMessage response
        {
            get
            {
                return this.responseField;
            }
            set
            {
                this.responseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentTypeIdByNameRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://njm.com/ccutil/1.0.0/interfaces", Order=0)]
        public OnBaseService.getDocumentTypeIdByName getDocumentTypeIdByName;
        
        public getDocumentTypeIdByNameRequest()
        {
        }
        
        public getDocumentTypeIdByNameRequest(OnBaseService.getDocumentTypeIdByName getDocumentTypeIdByName)
        {
            this.getDocumentTypeIdByName = getDocumentTypeIdByName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class getDocumentTypeIdByNameResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://njm.com/ccutil/1.0.0/interfaces", Order=0)]
        public OnBaseService.getDocumentTypeIdByNameResponse getDocumentTypeIdByNameResponse;
        
        public getDocumentTypeIdByNameResponse1()
        {
        }
        
        public getDocumentTypeIdByNameResponse1(OnBaseService.getDocumentTypeIdByNameResponse getDocumentTypeIdByNameResponse)
        {
            this.getDocumentTypeIdByNameResponse = getDocumentTypeIdByNameResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DocumentDataChannel : OnBaseService.DocumentData, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DocumentDataClient : System.ServiceModel.ClientBase<OnBaseService.DocumentData>, OnBaseService.DocumentData
    {
        
        public DocumentDataClient()
        {
        }
        
        public DocumentDataClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public DocumentDataClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DocumentDataClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public DocumentDataClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        OnBaseService.getDocumentTypeIdByNameResponse1 OnBaseService.DocumentData.getDocumentTypeIdByName(OnBaseService.getDocumentTypeIdByNameRequest request)
        {
            return base.Channel.getDocumentTypeIdByName(request);
        }
        
        public OnBaseService.getDocumentTypeIdByNameResponse getDocumentTypeIdByName(OnBaseService.getDocumentTypeIdByName getDocumentTypeIdByName1)
        {
            OnBaseService.getDocumentTypeIdByNameRequest inValue = new OnBaseService.getDocumentTypeIdByNameRequest();
            inValue.getDocumentTypeIdByName = getDocumentTypeIdByName1;
            OnBaseService.getDocumentTypeIdByNameResponse1 retVal = ((OnBaseService.DocumentData)(this)).getDocumentTypeIdByName(inValue);
            return retVal.getDocumentTypeIdByNameResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<OnBaseService.getDocumentTypeIdByNameResponse1> OnBaseService.DocumentData.getDocumentTypeIdByNameAsync(OnBaseService.getDocumentTypeIdByNameRequest request)
        {
            return base.Channel.getDocumentTypeIdByNameAsync(request);
        }
        
        public System.Threading.Tasks.Task<OnBaseService.getDocumentTypeIdByNameResponse1> getDocumentTypeIdByNameAsync(OnBaseService.getDocumentTypeIdByName getDocumentTypeIdByName)
        {
            OnBaseService.getDocumentTypeIdByNameRequest inValue = new OnBaseService.getDocumentTypeIdByNameRequest();
            inValue.getDocumentTypeIdByName = getDocumentTypeIdByName;
            return ((OnBaseService.DocumentData)(this)).getDocumentTypeIdByNameAsync(inValue);
        }
    }
}
