//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommercialMulti
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://njm.com/esb/ads/interfaces/AccountInfomationRetriever", ConfigurationName="CommercialMulti.AccountInfomationRetriever")]
    public interface AccountInfomationRetriever
    {
        
        // CODEGEN: Generating message contract since the operation retrieveAccountInformation is neither RPC nor document wrapped.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute()]
        CommercialMulti.retrieveAccountInformationResponse1 retrieveAccountInformation(CommercialMulti.retrieveAccountInformationRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<CommercialMulti.retrieveAccountInformationResponse1> retrieveAccountInformationAsync(CommercialMulti.retrieveAccountInformationRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://njm.com/esb/ads/interfaces/AccountInfomationRetriever")]
    public partial class retrieveAccountInformation
    {
        
        private RetrieveAccountInformationRequestMessage retrieveAccountInformationRequestMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://njm.com/esb/ads/types", Order=0)]
        public RetrieveAccountInformationRequestMessage RetrieveAccountInformationRequestMessage
        {
            get
            {
                return this.retrieveAccountInformationRequestMessageField;
            }
            set
            {
                this.retrieveAccountInformationRequestMessageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class RetrieveAccountInformationRequestMessage
    {
        
        private Header headerField;
        
        private string accountNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://njm.com/esb/common/types", Order=0)]
        public Header Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/types")]
    public partial class Header
    {
        
        private string versionField;
        
        private CorrelationContext correlationContextField;
        
        private Requestor requestorField;
        
        private bool errorInField;
        
        private bool errorInFieldSpecified;
        
        private ErrorInformation errorInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Version
        {
            get
            {
                return this.versionField;
            }
            set
            {
                this.versionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CorrelationContext CorrelationContext
        {
            get
            {
                return this.correlationContextField;
            }
            set
            {
                this.correlationContextField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public Requestor Requestor
        {
            get
            {
                return this.requestorField;
            }
            set
            {
                this.requestorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool ErrorIn
        {
            get
            {
                return this.errorInField;
            }
            set
            {
                this.errorInField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ErrorInSpecified
        {
            get
            {
                return this.errorInFieldSpecified;
            }
            set
            {
                this.errorInFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public ErrorInformation ErrorInformation
        {
            get
            {
                return this.errorInformationField;
            }
            set
            {
                this.errorInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/types")]
    public partial class CorrelationContext
    {
        
        private string correlationIdField;
        
        private CorrelationContextData dataField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string CorrelationId
        {
            get
            {
                return this.correlationIdField;
            }
            set
            {
                this.correlationIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public CorrelationContextData Data
        {
            get
            {
                return this.dataField;
            }
            set
            {
                this.dataField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/types")]
    public partial class CorrelationContextData
    {
        
        private System.Xml.XmlElement[] anyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyElementAttribute(Order=0)]
        public System.Xml.XmlElement[] Any
        {
            get
            {
                return this.anyField;
            }
            set
            {
                this.anyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class ServiceError
    {
        
        private string codeField;
        
        private string descriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class AccountDataServiceRequestDTO
    {
        
        private string accountNumberField;
        
        private string typeOfRequestField;
        
        private System.Nullable<System.DateTime> asOfDateField;
        
        private bool asOfDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string TypeOfRequest
        {
            get
            {
                return this.typeOfRequestField;
            }
            set
            {
                this.typeOfRequestField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<System.DateTime> AsOfDate
        {
            get
            {
                return this.asOfDateField;
            }
            set
            {
                this.asOfDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool AsOfDateSpecified
        {
            get
            {
                return this.asOfDateFieldSpecified;
            }
            set
            {
                this.asOfDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class ADSAddressDTO
    {
        
        private string addressLine1Field;
        
        private string addressLine2Field;
        
        private string addressLine3Field;
        
        private string cityField;
        
        private string countyField;
        
        private string postalCodeField;
        
        private string stateField;
        
        private string countryField;
        
        private string addressTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string AddressLine1
        {
            get
            {
                return this.addressLine1Field;
            }
            set
            {
                this.addressLine1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string AddressLine2
        {
            get
            {
                return this.addressLine2Field;
            }
            set
            {
                this.addressLine2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string AddressLine3
        {
            get
            {
                return this.addressLine3Field;
            }
            set
            {
                this.addressLine3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string City
        {
            get
            {
                return this.cityField;
            }
            set
            {
                this.cityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string County
        {
            get
            {
                return this.countyField;
            }
            set
            {
                this.countyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string PostalCode
        {
            get
            {
                return this.postalCodeField;
            }
            set
            {
                this.postalCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string State
        {
            get
            {
                return this.stateField;
            }
            set
            {
                this.stateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string Country
        {
            get
            {
                return this.countryField;
            }
            set
            {
                this.countryField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string AddressType
        {
            get
            {
                return this.addressTypeField;
            }
            set
            {
                this.addressTypeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class AccountRoleInformationDTO
    {
        
        private string nameField;
        
        private ADSAddressDTO roleAddressField;
        
        private string producerCodeField;
        
        private string emailField;
        
        private string phoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string Name
        {
            get
            {
                return this.nameField;
            }
            set
            {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public ADSAddressDTO RoleAddress
        {
            get
            {
                return this.roleAddressField;
            }
            set
            {
                this.roleAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string ProducerCode
        {
            get
            {
                return this.producerCodeField;
            }
            set
            {
                this.producerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public string Email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string Phone
        {
            get
            {
                return this.phoneField;
            }
            set
            {
                this.phoneField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class SubLineDTO
    {
        
        private string policyLineField;
        
        private System.Nullable<decimal> premiumField;
        
        private bool premiumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string PolicyLine
        {
            get
            {
                return this.policyLineField;
            }
            set
            {
                this.policyLineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public System.Nullable<decimal> Premium
        {
            get
            {
                return this.premiumField;
            }
            set
            {
                this.premiumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PremiumSpecified
        {
            get
            {
                return this.premiumFieldSpecified;
            }
            set
            {
                this.premiumFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class PolicyTransactionDetailsDTO
    {
        
        private string effectiveDateField;
        
        private string expirationDateField;
        
        private string quoteIDField;
        
        private SubLineDTO[] subLineInfoField;
        
        private string termTypeField;
        
        private string transactionStatusField;
        
        private string transactionTypeField;
        
        private string lineOfBusinessField;
        
        private string underwritingCompanyField;
        
        private System.Nullable<decimal> totalPremiumField;
        
        private bool totalPremiumFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=0)]
        public string EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=1)]
        public string ExpirationDate
        {
            get
            {
                return this.expirationDateField;
            }
            set
            {
                this.expirationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public string QuoteID
        {
            get
            {
                return this.quoteIDField;
            }
            set
            {
                this.quoteIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=3)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry")]
        public SubLineDTO[] SubLineInfo
        {
            get
            {
                return this.subLineInfoField;
            }
            set
            {
                this.subLineInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=4)]
        public string TermType
        {
            get
            {
                return this.termTypeField;
            }
            set
            {
                this.termTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=5)]
        public string TransactionStatus
        {
            get
            {
                return this.transactionStatusField;
            }
            set
            {
                this.transactionStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public string TransactionType
        {
            get
            {
                return this.transactionTypeField;
            }
            set
            {
                this.transactionTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public string LineOfBusiness
        {
            get
            {
                return this.lineOfBusinessField;
            }
            set
            {
                this.lineOfBusinessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=8)]
        public string UnderwritingCompany
        {
            get
            {
                return this.underwritingCompanyField;
            }
            set
            {
                this.underwritingCompanyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public System.Nullable<decimal> TotalPremium
        {
            get
            {
                return this.totalPremiumField;
            }
            set
            {
                this.totalPremiumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool TotalPremiumSpecified
        {
            get
            {
                return this.totalPremiumFieldSpecified;
            }
            set
            {
                this.totalPremiumFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class AccountInformationMessage
    {
        
        private string accountNumberField;
        
        private PolicyTransactionDetailsDTO[] policyTransactionsField;
        
        private System.Nullable<bool> isSuccessfulField;
        
        private bool isSuccessfulFieldSpecified;
        
        private AccountRoleInformationDTO accountHolderContactInfoField;
        
        private AccountRoleInformationDTO[] distributionPartnerInfoField;
        
        private AccountRoleInformationDTO[] distributionRepInfoField;
        
        private AccountDataServiceRequestDTO searchCriteriaRequestedField;
        
        private AccountDataServiceRequestDTO searchCriteriaUsedField;
        
        private AccountRoleInformationDTO[] underWriterInfoField;
        
        private ServiceError serviceErrorField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountNumber
        {
            get
            {
                return this.accountNumberField;
            }
            set
            {
                this.accountNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry")]
        public PolicyTransactionDetailsDTO[] PolicyTransactions
        {
            get
            {
                return this.policyTransactionsField;
            }
            set
            {
                this.policyTransactionsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=2)]
        public System.Nullable<bool> IsSuccessful
        {
            get
            {
                return this.isSuccessfulField;
            }
            set
            {
                this.isSuccessfulField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsSuccessfulSpecified
        {
            get
            {
                return this.isSuccessfulFieldSpecified;
            }
            set
            {
                this.isSuccessfulFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=3)]
        public AccountRoleInformationDTO AccountHolderContactInfo
        {
            get
            {
                return this.accountHolderContactInfoField;
            }
            set
            {
                this.accountHolderContactInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=4)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry")]
        public AccountRoleInformationDTO[] DistributionPartnerInfo
        {
            get
            {
                return this.distributionPartnerInfoField;
            }
            set
            {
                this.distributionPartnerInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=5)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry")]
        public AccountRoleInformationDTO[] DistributionRepInfo
        {
            get
            {
                return this.distributionRepInfoField;
            }
            set
            {
                this.distributionRepInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=6)]
        public AccountDataServiceRequestDTO SearchCriteriaRequested
        {
            get
            {
                return this.searchCriteriaRequestedField;
            }
            set
            {
                this.searchCriteriaRequestedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=7)]
        public AccountDataServiceRequestDTO SearchCriteriaUsed
        {
            get
            {
                return this.searchCriteriaUsedField;
            }
            set
            {
                this.searchCriteriaUsedField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true, Order=8)]
        [System.Xml.Serialization.XmlArrayItemAttribute("Entry")]
        public AccountRoleInformationDTO[] UnderWriterInfo
        {
            get
            {
                return this.underWriterInfoField;
            }
            set
            {
                this.underWriterInfoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=9)]
        public ServiceError ServiceError
        {
            get
            {
                return this.serviceErrorField;
            }
            set
            {
                this.serviceErrorField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/ads/types")]
    public partial class RetrieveAccountInformationResponseMessage
    {
        
        private Header headerField;
        
        private AccountInformationMessage accountInformationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://njm.com/esb/common/types", Order=0)]
        public Header Header
        {
            get
            {
                return this.headerField;
            }
            set
            {
                this.headerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public AccountInformationMessage AccountInformation
        {
            get
            {
                return this.accountInformationField;
            }
            set
            {
                this.accountInformationField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/types")]
    public partial class ErrorInformation
    {
        
        private string errorCdField;
        
        private string errorMessageField;
        
        private ErrorInformation causeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCd
        {
            get
            {
                return this.errorCdField;
            }
            set
            {
                this.errorCdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMessage
        {
            get
            {
                return this.errorMessageField;
            }
            set
            {
                this.errorMessageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public ErrorInformation Cause
        {
            get
            {
                return this.causeField;
            }
            set
            {
                this.causeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://njm.com/esb/common/types")]
    public partial class Requestor
    {
        
        private string systemIdentityField;
        
        private string userIdentityField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string SystemIdentity
        {
            get
            {
                return this.systemIdentityField;
            }
            set
            {
                this.systemIdentityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string UserIdentity
        {
            get
            {
                return this.userIdentityField;
            }
            set
            {
                this.userIdentityField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("svcutil", "4.8.3928.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://njm.com/esb/ads/interfaces/AccountInfomationRetriever")]
    public partial class retrieveAccountInformationResponse
    {
        
        private RetrieveAccountInformationResponseMessage retrieveAccountInformationResponseMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Namespace="http://njm.com/esb/ads/types", Order=0)]
        public RetrieveAccountInformationResponseMessage RetrieveAccountInformationResponseMessage
        {
            get
            {
                return this.retrieveAccountInformationResponseMessageField;
            }
            set
            {
                this.retrieveAccountInformationResponseMessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveAccountInformationRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://njm.com/esb/ads/interfaces/AccountInfomationRetriever", Order=0)]
        public CommercialMulti.retrieveAccountInformation retrieveAccountInformation;
        
        public retrieveAccountInformationRequest()
        {
        }
        
        public retrieveAccountInformationRequest(CommercialMulti.retrieveAccountInformation retrieveAccountInformation)
        {
            this.retrieveAccountInformation = retrieveAccountInformation;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class retrieveAccountInformationResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://njm.com/esb/ads/interfaces/AccountInfomationRetriever", Order=0)]
        public CommercialMulti.retrieveAccountInformationResponse retrieveAccountInformationResponse;
        
        public retrieveAccountInformationResponse1()
        {
        }
        
        public retrieveAccountInformationResponse1(CommercialMulti.retrieveAccountInformationResponse retrieveAccountInformationResponse)
        {
            this.retrieveAccountInformationResponse = retrieveAccountInformationResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AccountInfomationRetrieverChannel : CommercialMulti.AccountInfomationRetriever, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AccountInfomationRetrieverClient : System.ServiceModel.ClientBase<CommercialMulti.AccountInfomationRetriever>, CommercialMulti.AccountInfomationRetriever
    {
        
        public AccountInfomationRetrieverClient()
        {
        }
        
        public AccountInfomationRetrieverClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public AccountInfomationRetrieverClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AccountInfomationRetrieverClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public AccountInfomationRetrieverClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        CommercialMulti.retrieveAccountInformationResponse1 CommercialMulti.AccountInfomationRetriever.retrieveAccountInformation(CommercialMulti.retrieveAccountInformationRequest request)
        {
            return base.Channel.retrieveAccountInformation(request);
        }
        
        public CommercialMulti.retrieveAccountInformationResponse retrieveAccountInformation(CommercialMulti.retrieveAccountInformation retrieveAccountInformation1)
        {
            CommercialMulti.retrieveAccountInformationRequest inValue = new CommercialMulti.retrieveAccountInformationRequest();
            inValue.retrieveAccountInformation = retrieveAccountInformation1;
            CommercialMulti.retrieveAccountInformationResponse1 retVal = ((CommercialMulti.AccountInfomationRetriever)(this)).retrieveAccountInformation(inValue);
            return retVal.retrieveAccountInformationResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<CommercialMulti.retrieveAccountInformationResponse1> CommercialMulti.AccountInfomationRetriever.retrieveAccountInformationAsync(CommercialMulti.retrieveAccountInformationRequest request)
        {
            return base.Channel.retrieveAccountInformationAsync(request);
        }
        
        public System.Threading.Tasks.Task<CommercialMulti.retrieveAccountInformationResponse1> retrieveAccountInformationAsync(CommercialMulti.retrieveAccountInformation retrieveAccountInformation)
        {
            CommercialMulti.retrieveAccountInformationRequest inValue = new CommercialMulti.retrieveAccountInformationRequest();
            inValue.retrieveAccountInformation = retrieveAccountInformation;
            return ((CommercialMulti.AccountInfomationRetriever)(this)).retrieveAccountInformationAsync(inValue);
        }
    }
}
